"""
Example usage 

UniD3 prompt: "Give me information about the drug ANTIMICROBIAL?"
RepoDB Prompt: "What is drug ajmaline's drugbank_id?"
FAERS Prompt: "What are the top 5 most common adverse events reported for the drug IBUPROFEN?"
DRUGMECHDB Prompt: "What is the mechanism of action of the drug metformin according to DRUGMECHDB? Only use DRUGMECHDB skill to answer"
openFDA Human Drug Prompt: "What are the approved indications for the drug sertraline according to openFDA? Only use openFDA Human Drug skill to answer"
DailyMed Prompt: "What are the active ingredients and their strengths in the drug Lipitor according to DailyMed? Only use DailyMed skill to answer"
DrugBank Prompt: "What are the known drug interactions for the drug warfarin according to DrugBank? Only use DrugBank skill to answer"
RxNorm Prompt: "What are the available dosage forms and strengths for the drug amoxicillin according to RxNorm? Only use RxNorm skill to answer"
DrugEHRQA Prompt: "What are the common side effects of the drug prednisone based on real-world EHR data in DrugEHRQA? Only use DrugEHRQA skill to answer"
WebMD Drug Reviews Prompt: "What are the common patient-reported side effects of the drug fluoxetine according to WebMD Drug Reviews? Only use WebMD Drug Reviews skill to answer"
ChEMBL Prompt: "What are the bioactivity data for the drug imatinib according to ChEMBL? Only use ChEMBL skill to answer"
Open Targets Platform Prompt: "What diseases are associated with the drug tofacitinib according to the Open Targets Platform? Only use Open Targets Platform skill to answer"
IUPHAR/BPS Guide to Pharmacology Prompt: "What are the known targets and their pharmacological classifications for the drug propranolol according to IUPHAR/BPS Guide to Pharmacology? Only use IUPHAR/BPS Guide to Pharmacology skill to answer"
SIDER Prompt: "What are the known side effects of the drug cisplatin according to SIDER? Only use SIDER skill to answer"
nSIDES Prompt: "What are the known side effects of the drug cisplatin according to nSIDES? Only use nSIDES skill to answer"
DGIdb Prompt: "What are the known targets for the drug aspirin according to DGIdb? Only use DGIdb skill to answer"
TTD Prompt: "What are the known targets for the drug tamoxifen according to TTD? Only use TTD skill to answer"
DrugCentral Prompt: "What are the known side effects of the drug paracetamol according to DrugCentral? Only use DrugCentral skill to answer"
MecDDI Prompt: "What are the known drug-drug interactions for the drug clopidogrel according to MecDDI? Only use MecDDI skill to answer"
DDInter Prompt: "What are the known drug-drug interactions for the drug simvastatin according to DDInter? Only use DDInter skill to answer"
DrugCombDB Prompt: "What are the known drug combinations involving the drug trastuzumab according to DrugCombDB? Only use DrugCombDB skill to answer"
CDCDB Prompt: "What are the known drug combinations involving the drug trastuzumab according to CDCDB? Only use CDCDB skill to answer"
VigiAccess Prompt: "What are the known adverse drug reactions for the drug ibuprofen according to VigiAccess? Only use VigiAccess skill to answer"
OREGANO Prompt: "What are the known drug-drug interactions for the drug clopidogrel according to OREGANO? Only use OREGANO skill to answer"
DRKG Prompt: "What are the known drug-disease associations for the drug metformin according to DRKG? Only use DRKG skill to answer"
BindingDB Prompt: "What are the known binding affinities for the drug imatinib according to BindingDB? Only use BindingDB skill to answer"
ATC/DDD Prompt: "What is the ATC classification and defined daily dose for the drug amlodipine according to ATC/DDD? Only use ATC/DDD skill to answer"
UniTox Prompt: "What are the known toxicological effects of the drug acetaminophen according to UniTox? Only use UniTox skill to answer"
Drug Repurposing Hub Prompt: "What are the known repurposing opportunities for the drug metformin according to the Drug Repurposing Hub? Only use Drug Repurposing Hub skill to answer"
DDI Corpus 2013 Prompt: "What are the known drug-drug interactions for the drug clopidogrel according to the DDI Corpus 2013? Only use DDI Corpus 2013 skill to answer"
DrugProt Prompt: "What are the known drug-protein interactions for the drug imatinib according to DrugProt? Only use DrugProt skill to answer"
ADE Corpus 2019 Prompt: "What are the known adverse drug events for the drug warfarin according to ADE Corpus 2019? Only use ADE Corpus 2019 skill to answer"
n2c2 2018 Track 2 Prompt: "What are the known drug-disease associations for the drug metformin according to n2c2 2018 Track 2? Only use n2c2 2018 Track 2 skill to answer"
CADEC Prompt: "What are the known adverse drug events for the drug ibuprofen according to CADEC? Only use CADEC skill to answer"
askapatient Prompt: "What are the common patient-reported side effects of the drug fluoxetine according to askapatient? Only use askapatient skill to answer"
PsyTAR Prompt: "What are the common patient-reported side effects of the drug fluoxetine according to PsyTAR? Only use PsyTAR skill to answer"
TAC 2017 ADR Prompt: "What are the known adverse drug reactions for the drug ibuprofen according to TAC 2017 ADR? Only use TAC 2017 ADR skill to answer"
PHEE Prompt: "What are the known drug-drug interactions for the drug clopidogrel according to PHEE? Only use PHEE skill to answer"
Drugs.com Prompt: "What are the common patient-reported side effects of the drug fluoxetine according to Drugs.com? Only use Drugs.com skill to answer"
Drug Reviews (Drugs.com) Prompt: "What are the common patient-reported side effects of the drug fluoxetine according to Drug Reviews on Drugs.com? Only use Drug Reviews (Drugs.com) skill to answer"
TarKG Prompt: "What are the known drug-target interactions for the drug imatinib according to TarKG? Only use TarKG skill to answer"
DrugRepoBank Prompt: "What are the known drug repositories for the drug metformin according to DrugRepoBank? Only use DrugRepoBank skill to answer"
RepurposeDrugs Prompt: "What are the known repurposing opportunities for the drug metformin according to RepurposeDrugs? Only use RepurposeDrugs skill to answer"
DrugRepurposing Online Prompt: "What are the known repurposing opportunities for the drug metformin according to DrugRepurposing Online? Only use DrugRepurposing Online skill to answer"
STITCH Prompt: "What are the known drug interactions for the drug clopidogrel according to STITCH? Only use STITCH skill to answer"
PROMISCUOUS 2.0 Prompt: "What are the known drug interactions for the drug clopidogrel according to PROMISCUOUS 2.0? Only use PROMISCUOUS 2.0 skill to answer"
LiverTox Prompt: "What are the known hepatotoxic effects of the drug acetaminophen according to LiverTox? Only use LiverTox skill to answer"
DILIrank Prompt: "What are the known drug-induced liver injury risks for the drug acetaminophen according to DILIrank? Only use DILIrank skill to answer"
PharmGKB/ClinPGx Prompt: "What are the known pharmacogenomic associations for the drug clopidogrel according to PharmGKB/ClinPGx? Only use PharmGKB/ClinPGx skill to answer"
DrugComb Prompt: "What are the known drug combinations involving the drug trastuzumab according to DrugComb? Only use DrugComb skill to answer"
DCDB (Drug Combination DB) Prompt: "What are the known drug combinations involving the drug trastuzumab according to DCDB? Only use DCDB skill to answer"
NDF-RT (National Drug File) Prompt: "What are the known drug classifications and properties for the drug amoxicillin according to NDF-RT? Only use NDF-RT skill to answer"
CancerDR Prompt: "What are the known drug resistance mechanisms for the drug imatinib in cancer according to CancerDR? Only use CancerDR skill to answer"
GDKD (Genomics-Drug Knowledge DB) Prompt: "What are the known genomics-drug associations for the drug imatinib according to GDKD? Only use GDKD skill to answer"
PharmKG Prompt: "What are the known drug-gene-disease associations for the drug metformin according to PharmKG? Only use PharmKG skill to answer"
RxList Drug Descriptions Prompt: "What are the known drug descriptions for the drug metformin according to RxList? Only use RxList skill to answer"
MedlinePlus Drug Info Prompt: "What are the known drug information for the drug metformin according to MedlinePlus? Only use MedlinePlus skill to answer"
WHO Essential Medicines List Prompt: "What are the known essential medicines for the drug metformin according to WHO? Only use WHO skill to answer"
EK-DRD Prompt: "What are the known drug interactions for the drug metformin according to EK-DRD? Only use EK-DRD skill to answer"
GDSC/GDSC2 Prompt: "What are the known drug responses for the drug metformin according to GDSC/GDSC2? Only use GDSC/GDSC2 skill to answer"
DILI (Drug-Induced Liver Injury) Prompt: "What are the known drug-induced liver injury risks for the drug metformin according to DILI? Only use DILI skill to answer"
ADReCS Prompt: "What are the known adverse drug reactions for the drug metformin according to ADReCS? Only use ADReCS skill to answer"
DTC (Drug Target Commons) 2.0/DTC (Drug Target Commons) Prompt: "What are the known drug-target interactions for the drug metformin according to DTC (Drug Target Commons) 2.0? Only use DTC (Drug Target Commons) 2.0 skill to answer"
ChEBI Prompt: "What are the known chemical properties and classifications for the drug metformin according to ChEBI? Only use ChEBI skill to answer"
FDA Orange Book Prompt: "What are the known approved drug products for the drug metformin according to the FDA Orange Book? Only use FDA Orange Book skill to answer"
SemaTyP Prompt: "What are the known drug-target interactions for the drug metformin according to SemaTyP? Only use SemaTyP skill to answer"
CPIC Prompt: "What are the known pharmacogenomic guidelines for the drug clopidogrel according to CPIC? Only use CPIC skill to answer"
KEGG Drug Prompt: "What are the known drug pathways and interactions for the drug metformin according to KEGG Drug? Only use KEGG Drug skill to answer"
"""